spring.application.name=ai-eorg

# src/main/resources/application.properties

# DataSource settings
spring.datasource.url=jdbc:postgresql://postgresdb:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Additional PostgreSQL specific settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update 

#AI API keys are envorin variables
spring.ai.mistralai.api-key=${MISTRAL_API_KEY}
#spring.ai.mistralai.base-url=https://api.mistral.ai/v1